# Generated by Django 4.0.5 on 2022-06-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='', max_length=250)),
                ('uploaded_by', models.IntegerField()),
                ('file_status', models.IntegerField()),
                ('uploaded_date', models.DateTimeField()),
                ('last_modified_date', models.DateTimeField()),
                ('last_modified_by', models.IntegerField()),
                ('is_delete', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'file',
            },
        ),
    ]
